name:Build abd Publish image to Docker Hub
on:
  [workflow_dispatch]
  
jobs:
 publish_images:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: build image
    run: docker build .

  - name: Build and push APK
 